version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: shop_web
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py loaddata fixtures/categories.json &&
      python manage.py loaddata fixtures/products.json &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: shop_db
      DB_USER: shop_user
      DB_PASSWORD: shop_password

volumes:
  postgres_data: