# Generated by Django 4.2.25 on 2026-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_on_get",
            field=models.BooleanField(default=False, verbose_name="Оплата наличными"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Количество"
            ),
        ),
    ]
